// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/testing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestCaseInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Categories     []string               `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Difficulty     string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestCaseInfo) Reset() {
	*x = TestCaseInfo{}
	mi := &file_proto_testing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseInfo) ProtoMessage() {}

func (x *TestCaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseInfo.ProtoReflect.Descriptor instead.
func (*TestCaseInfo) Descriptor() ([]byte, []int) {
	return file_proto_testing_proto_rawDescGZIP(), []int{0}
}

func (x *TestCaseInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TestCaseInfo) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *TestCaseInfo) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TestCaseInfo) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TestCaseInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TestCaseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Hints         map[string]string      `protobuf:"bytes,3,rep,name=hints,proto3" json:"hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCaseData) Reset() {
	*x = TestCaseData{}
	mi := &file_proto_testing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCaseData) ProtoMessage() {}

func (x *TestCaseData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCaseData.ProtoReflect.Descriptor instead.
func (*TestCaseData) Descriptor() ([]byte, []int) {
	return file_proto_testing_proto_rawDescGZIP(), []int{1}
}

func (x *TestCaseData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TestCaseData) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TestCaseData) GetHints() map[string]string {
	if x != nil {
		return x.Hints
	}
	return nil
}

type SubmitSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestCaseId    string                 `protobuf:"bytes,1,opt,name=test_case_id,json=testCaseId,proto3" json:"test_case_id,omitempty"`
	Response      []byte                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSolutionRequest) Reset() {
	*x = SubmitSolutionRequest{}
	mi := &file_proto_testing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionRequest) ProtoMessage() {}

func (x *SubmitSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionRequest.ProtoReflect.Descriptor instead.
func (*SubmitSolutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_testing_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitSolutionRequest) GetTestCaseId() string {
	if x != nil {
		return x.TestCaseId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SubmitSolutionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SubmitSolutionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Valid           bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Score           float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details         map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics         map[string]float64     `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ExecutionTimeMs int64                  `protobuf:"varint,6,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitSolutionResponse) Reset() {
	*x = SubmitSolutionResponse{}
	mi := &file_proto_testing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionResponse) ProtoMessage() {}

func (x *SubmitSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionResponse.ProtoReflect.Descriptor instead.
func (*SubmitSolutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_testing_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitSolutionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *SubmitSolutionResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitSolutionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitSolutionResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *SubmitSolutionResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SubmitSolutionResponse) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

type ListTestCasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Difficulty    string                 `protobuf:"bytes,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTestCasesRequest) Reset() {
	*x = ListTestCasesRequest{}
	mi := &file_proto_testing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTestCasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestCasesRequest) ProtoMessage() {}

func (x *ListTestCasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestCasesRequest.ProtoReflect.Descriptor instead.
func (*ListTestCasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_testing_proto_rawDescGZIP(), []int{4}
}

func (x *ListTestCasesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListTestCasesRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *ListTestCasesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTestCasesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListTestCasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestCases     []*TestCaseInfo        `protobuf:"bytes,1,rep,name=test_cases,json=testCases,proto3" json:"test_cases,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTestCasesResponse) Reset() {
	*x = ListTestCasesResponse{}
	mi := &file_proto_testing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTestCasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTestCasesResponse) ProtoMessage() {}

func (x *ListTestCasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTestCasesResponse.ProtoReflect.Descriptor instead.
func (*ListTestCasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_testing_proto_rawDescGZIP(), []int{5}
}

func (x *ListTestCasesResponse) GetTestCases() []*TestCaseInfo {
	if x != nil {
		return x.TestCases
	}
	return nil
}

func (x *ListTestCasesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetTestCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestCaseRequest) Reset() {
	*x = GetTestCaseRequest{}
	mi := &file_proto_testing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestCaseRequest) ProtoMessage() {}

func (x *GetTestCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestCaseRequest.ProtoReflect.Descriptor instead.
func (*GetTestCaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_testing_proto_rawDescGZIP(), []int{6}
}

func (x *GetTestCaseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTestCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *TestCaseInfo          `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Data          *TestCaseData          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestCaseResponse) Reset() {
	*x = GetTestCaseResponse{}
	mi := &file_proto_testing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestCaseResponse) ProtoMessage() {}

func (x *GetTestCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestCaseResponse.ProtoReflect.Descriptor instead.
func (*GetTestCaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_testing_proto_rawDescGZIP(), []int{7}
}

func (x *GetTestCaseResponse) GetInfo() *TestCaseInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetTestCaseResponse) GetData() *TestCaseData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_testing_proto protoreflect.FileDescriptor

const file_proto_testing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/testing.proto\x12\x05proto\"\xa5\x02\n" +
	"\fTestCaseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\x12=\n" +
	"\bmetadata\x18\x06 \x03(\v2!.proto.TestCaseInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\fTestCaseData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x124\n" +
	"\x05hints\x18\x03 \x03(\v2\x1e.proto.TestCaseData.HintsEntryR\x05hints\x1a8\n" +
	"\n" +
	"HintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\x15SubmitSolutionRequest\x12 \n" +
	"\ftest_case_id\x18\x01 \x01(\tR\n" +
	"testCaseId\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\fR\bresponse\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.proto.SubmitSolutionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x03\n" +
	"\x16SubmitSolutionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12D\n" +
	"\adetails\x18\x04 \x03(\v2*.proto.SubmitSolutionResponse.DetailsEntryR\adetails\x12D\n" +
	"\ametrics\x18\x05 \x03(\v2*.proto.SubmitSolutionResponse.MetricsEntryR\ametrics\x12*\n" +
	"\x11execution_time_ms\x18\x06 \x01(\x03R\x0fexecutionTimeMs\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x84\x01\n" +
	"\x14ListTestCasesRequest\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\tR\n" +
	"difficulty\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"l\n" +
	"\x15ListTestCasesResponse\x122\n" +
	"\n" +
	"test_cases\x18\x01 \x03(\v2\x13.proto.TestCaseInfoR\ttestCases\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"$\n" +
	"\x12GetTestCaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x13GetTestCaseResponse\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x13.proto.TestCaseInfoR\x04info\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x13.proto.TestCaseDataR\x04data2\xf1\x01\n" +
	"\x0eTestingService\x12J\n" +
	"\rListTestCases\x12\x1b.proto.ListTestCasesRequest\x1a\x1c.proto.ListTestCasesResponse\x12D\n" +
	"\vGetTestCase\x12\x19.proto.GetTestCaseRequest\x1a\x1a.proto.GetTestCaseResponse\x12M\n" +
	"\x0eSubmitSolution\x12\x1c.proto.SubmitSolutionRequest\x1a\x1d.proto.SubmitSolutionResponseB$Z\"github.com/jalphad/testforge/protob\x06proto3"

var (
	file_proto_testing_proto_rawDescOnce sync.Once
	file_proto_testing_proto_rawDescData []byte
)

func file_proto_testing_proto_rawDescGZIP() []byte {
	file_proto_testing_proto_rawDescOnce.Do(func() {
		file_proto_testing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_testing_proto_rawDesc), len(file_proto_testing_proto_rawDesc)))
	})
	return file_proto_testing_proto_rawDescData
}

var file_proto_testing_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_testing_proto_goTypes = []any{
	(*TestCaseInfo)(nil),           // 0: proto.TestCaseInfo
	(*TestCaseData)(nil),           // 1: proto.TestCaseData
	(*SubmitSolutionRequest)(nil),  // 2: proto.SubmitSolutionRequest
	(*SubmitSolutionResponse)(nil), // 3: proto.SubmitSolutionResponse
	(*ListTestCasesRequest)(nil),   // 4: proto.ListTestCasesRequest
	(*ListTestCasesResponse)(nil),  // 5: proto.ListTestCasesResponse
	(*GetTestCaseRequest)(nil),     // 6: proto.GetTestCaseRequest
	(*GetTestCaseResponse)(nil),    // 7: proto.GetTestCaseResponse
	nil,                            // 8: proto.TestCaseInfo.MetadataEntry
	nil,                            // 9: proto.TestCaseData.HintsEntry
	nil,                            // 10: proto.SubmitSolutionRequest.MetadataEntry
	nil,                            // 11: proto.SubmitSolutionResponse.DetailsEntry
	nil,                            // 12: proto.SubmitSolutionResponse.MetricsEntry
}
var file_proto_testing_proto_depIdxs = []int32{
	8,  // 0: proto.TestCaseInfo.metadata:type_name -> proto.TestCaseInfo.MetadataEntry
	9,  // 1: proto.TestCaseData.hints:type_name -> proto.TestCaseData.HintsEntry
	10, // 2: proto.SubmitSolutionRequest.metadata:type_name -> proto.SubmitSolutionRequest.MetadataEntry
	11, // 3: proto.SubmitSolutionResponse.details:type_name -> proto.SubmitSolutionResponse.DetailsEntry
	12, // 4: proto.SubmitSolutionResponse.metrics:type_name -> proto.SubmitSolutionResponse.MetricsEntry
	0,  // 5: proto.ListTestCasesResponse.test_cases:type_name -> proto.TestCaseInfo
	0,  // 6: proto.GetTestCaseResponse.info:type_name -> proto.TestCaseInfo
	1,  // 7: proto.GetTestCaseResponse.data:type_name -> proto.TestCaseData
	4,  // 8: proto.TestingService.ListTestCases:input_type -> proto.ListTestCasesRequest
	6,  // 9: proto.TestingService.GetTestCase:input_type -> proto.GetTestCaseRequest
	2,  // 10: proto.TestingService.SubmitSolution:input_type -> proto.SubmitSolutionRequest
	5,  // 11: proto.TestingService.ListTestCases:output_type -> proto.ListTestCasesResponse
	7,  // 12: proto.TestingService.GetTestCase:output_type -> proto.GetTestCaseResponse
	3,  // 13: proto.TestingService.SubmitSolution:output_type -> proto.SubmitSolutionResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_testing_proto_init() }
func file_proto_testing_proto_init() {
	if File_proto_testing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_testing_proto_rawDesc), len(file_proto_testing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_testing_proto_goTypes,
		DependencyIndexes: file_proto_testing_proto_depIdxs,
		MessageInfos:      file_proto_testing_proto_msgTypes,
	}.Build()
	File_proto_testing_proto = out.File
	file_proto_testing_proto_goTypes = nil
	file_proto_testing_proto_depIdxs = nil
}
